import type { InsertPepper } from "@shared/schema";

// We use the *raw* shape (arrays, not yet JSON.stringified) so we can be readable.
type SeedPepper = Omit<InsertPepper, "flavor_tags" | "flavor_subtags" | "color_tags" | "use_cases"> & {
  flavor_tags: string[];
  flavor_subtags: string[];
  color_tags: string[];
  use_cases: string[];
};

const tenGalFabric = "10 gal";
const tenGalPlastic = "10 gal";
const sevenGalFabric = "7 gal";
const fiveGal = "5 gal";
const bucket = "10 gal";

function p(o: Partial<SeedPepper> & { cultivar: string; plant_code: string }): SeedPepper {
  return {
    cultivar: o.cultivar,
    plant_code: o.plant_code,
    species: o.species ?? "chinense",
    heat_level: o.heat_level ?? 3,
    flavor_tags: o.flavor_tags ?? [],
    flavor_subtags: o.flavor_subtags ?? [],
    color_tags: o.color_tags ?? ["red"],
    age: o.age ?? "seedling",
    status: o.status ?? "Ready to transplant",
    current_pot: o.current_pot ?? "Cups / unassigned",
    recommended_pot: o.recommended_pot ?? tenGalFabric,
    ideal_pot: o.ideal_pot ?? tenGalFabric,
    pot_material: o.pot_material ?? "cup",
    location: o.location ?? "Rooftop",
    thumbnail: o.thumbnail ?? "🌶️",
    description: o.description ?? "",
    special: o.special ?? "",
    notes: o.notes ?? "",
    priority: o.priority ?? "normal",
    use_cases: o.use_cases ?? [],
    fixed: o.fixed ?? false,
    seeded: true,
  };
}

export const SEED_PEPPERS: SeedPepper[] = [
  // ========== FIXED / ESTABLISHED PLANTS ==========
  p({
    cultivar: "White Habanero",
    plant_code: "OW",
    species: "chinense",
    heat_level: 4,
    flavor_tags: ["aromatic/perfume", "fruity"],
    flavor_subtags: ["tropical", "incense"],
    color_tags: ["white/cream"],
    age: "OW 2yr+",
    status: "Fixed - established",
    current_pot: tenGalPlastic,
    recommended_pot: tenGalPlastic,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "⚪",
    description: "Pale, ghost-white habanero with classic floral chinense burn and tropical sweetness.",
    special: "Rare ghostly color stays cream-white at full ripeness.",
    notes: "Already in 10-gal fabric pot. Do not reallocate.",
    priority: "high",
    use_cases: ["hot sauce", "fresh eat", "seed save"],
    fixed: true,
  }),
  p({
    cultivar: "Chocolate Habanero",
    plant_code: "OW",
    species: "chinense",
    heat_level: 4,
    flavor_tags: ["earthy", "smoky", "fruity"],
    flavor_subtags: ["raisin", "tropical"],
    color_tags: ["brown"],
    age: "OW 2yr+",
    status: "Fixed - established",
    current_pot: tenGalPlastic,
    recommended_pot: tenGalPlastic,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "chocolate-bar",
    description: "Deep brown habanero with smoky raisin notes and a hot, fruity finish.",
    special: "Chocolate color and rich raisin depth most habs lack.",
    notes: "Already in 10-gal fabric pot. Do not reallocate.",
    priority: "high",
    use_cases: ["hot sauce", "dehydrate/powder"],
    fixed: true,
  }),
  p({
    cultivar: "Red Jamaican",
    plant_code: "OW",
    species: "chinense",
    heat_level: 4,
    flavor_tags: ["fruity", "aromatic/perfume"],
    flavor_subtags: ["tropical", "exotic"],
    color_tags: ["red"],
    age: "2 years",
    status: "Fixed - established",
    current_pot: tenGalPlastic,
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "plastic bucket (light)",
    thumbnail: "🔴",
    description: "Caribbean-style scorching red habanero relative with bright tropical perfume.",
    special: "OW 2-year survivor upgraded into the extra 10-gal bucket.",
    notes: "Upgraded from 5 gal into the extra 10-gal bucket.",
    priority: "high",
    use_cases: ["hot sauce", "fresh eat"],
    fixed: true,
  }),
  p({
    cultivar: "Devil's Tongue x Scorpion Orange",
    plant_code: "OW",
    species: "chinense",
    heat_level: 5,
    flavor_tags: ["fruity", "citrus", "floral"],
    flavor_subtags: ["tropical", "orange", "rose"],
    color_tags: ["orange"],
    age: "mature",
    status: "Fixed - established",
    current_pot: tenGalFabric,
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🦂",
    description: "Orange chinense cross with superhot sting, citrus fruit, and floral Devil's Tongue perfume.",
    special: "Superhot orange cross already established in 10-gal fabric.",
    notes: "Already in 10-gal fabric pot. Do not reallocate.",
    priority: "high",
    use_cases: ["hot sauce", "dehydrate/powder", "seed save"],
    fixed: true,
  }),
  p({
    cultivar: "Aji Norteno",
    plant_code: "OW",
    species: "baccatum",
    heat_level: 3,
    flavor_tags: ["fruity", "citrus"],
    flavor_subtags: ["tropical", "lemon"],
    color_tags: ["red"],
    age: "2 years",
    status: "Fixed - established",
    current_pot: bucket,
    recommended_pot: bucket,
    ideal_pot: tenGalFabric,
    pot_material: "plastic bucket (light)",
    thumbnail: "red-fang",
    description: "Andean baccatum with bright lemon-tropical zing and a moderate clean burn.",
    special: "OW 2-year and very productive once mature.",
    notes: "Transplanted into 8-10 gal bucket. Keep fixed.",
    priority: "high",
    use_cases: ["fresh eat", "salsa", "ferment"],
    fixed: true,
  }),
  p({
    cultivar: "Aji Cristal",
    plant_code: "OW",
    species: "baccatum",
    heat_level: 3,
    flavor_tags: ["fruity", "citrus", "vegetal/savory"],
    flavor_subtags: ["lemon", "grassy"],
    color_tags: ["green", "yellow", "red"],
    age: "1 year",
    status: "Fixed - established",
    current_pot: bucket,
    recommended_pot: bucket,
    ideal_pot: tenGalFabric,
    pot_material: "plastic bucket (light)",
    thumbnail: "🟢",
    description: "Crystal-clear Chilean baccatum, crisp and citrusy when green, sweeter when ripe.",
    special: "Works green or red — staggered harvests.",
    notes: "Transplanted into 8-10 gal bucket.",
    priority: "high",
    use_cases: ["fresh eat", "salsa"],
    fixed: true,
  }),
  p({
    cultivar: "Bishop's Crown",
    plant_code: "OW",
    species: "baccatum",
    heat_level: 2,
    flavor_tags: ["fruity", "sweet"],
    flavor_subtags: ["peachy", "honey"],
    color_tags: ["red"],
    age: "2 years",
    status: "Fixed - established",
    current_pot: bucket,
    recommended_pot: bucket,
    ideal_pot: tenGalFabric,
    pot_material: "plastic bucket (light)",
    thumbnail: "👑",
    description: "Three-winged crown-shaped pod, sweet apple-pear flavor with mild lingering heat.",
    special: "Iconic crown shape — most photogenic plant on the roof.",
    notes: "Transplanted into 8-10 gal bucket.",
    priority: "high",
    use_cases: ["fresh eat", "ornamental", "stuffing"],
    fixed: true,
  }),

  // ========== OW PRIORITY PLANTS — 10 gal fabric ==========
  p({
    cultivar: "Pimenta De Neyde",
    plant_code: "OW",
    species: "chinense",
    heat_level: 4,
    flavor_tags: ["fruity", "floral"],
    flavor_subtags: ["berry", "rose"],
    color_tags: ["purple/pink"],
    age: "OW 2yr+",
    status: "Transplanted",
    current_pot: tenGalFabric,
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🟣",
    description: "Stunning all-black plant with deep purple pods ripening to red — floral berry heat.",
    special: "Black foliage and stems — visual showstopper.",
    notes: "Best in 10-gal fabric to support its lush bushy frame.",
    priority: "high",
    use_cases: ["ornamental", "hot sauce", "seed save"],
  }),
  p({
    cultivar: "Aji Mango",
    plant_code: "OW",
    species: "baccatum",
    heat_level: 3,
    flavor_tags: ["fruity", "sweet"],
    flavor_subtags: ["tropical", "peachy"],
    color_tags: ["orange", "yellow"],
    age: "OW 2yr+",
    status: "Transplanted",
    current_pot: tenGalFabric,
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🥭",
    description: "Mango-sweet baccatum, tropical and juicy with a clean medium burn.",
    special: "Tastes literally like ripe mango.",
    notes: "Heavy yielder — give it the room.",
    priority: "high",
    use_cases: ["fresh eat", "hot sauce", "ferment"],
  }),
  p({
    cultivar: "Moruga Sweet",
    plant_code: "OW",
    species: "chinense",
    heat_level: 1,
    flavor_tags: ["fruity", "sweet", "aromatic/perfume"],
    flavor_subtags: ["tropical", "incense"],
    color_tags: ["red"],
    age: "OW 2yr+",
    status: "Transplanted",
    current_pot: tenGalFabric,
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🍬",
    description: "Heatless cousin of the Moruga Scorpion — full chinense aroma without the burn.",
    special: "Family-friendly chinense flavor; no heat penalty.",
    notes: "Performs best in 10-gal fabric.",
    priority: "high",
    use_cases: ["fresh eat", "salsa", "stuffing"],
  }),
  p({
    cultivar: "Naga Cream",
    plant_code: "OW",
    species: "chinense",
    heat_level: 4,
    flavor_tags: ["aromatic/perfume", "fruity"],
    flavor_subtags: ["tropical", "incense"],
    color_tags: ["white/cream"],
    age: "OW 2yr+",
    status: "Transplanted",
    current_pot: tenGalPlastic,
    recommended_pot: tenGalPlastic,
    ideal_pot: tenGalFabric,
    pot_material: "plastic bucket (light)",
    thumbnail: "🍦",
    description: "Cream-colored Naga with explosive perfume and superhot-adjacent heat.",
    special: "Pale cream pods are unusual and striking.",
    notes: "Uses one of the 2 remaining 10-gal plastic buckets for steadier moisture.",
    priority: "high",
    use_cases: ["hot sauce", "dehydrate/powder"],
  }),
  p({
    cultivar: "Sugar Rush Amarillo",
    plant_code: "OW",
    species: "baccatum",
    heat_level: 2,
    flavor_tags: ["fruity", "sweet", "citrus"],
    flavor_subtags: ["tropical", "lemon"],
    color_tags: ["yellow"],
    age: "OW 2yr+",
    status: "Transplanted",
    current_pot: sevenGalFabric,
    recommended_pot: sevenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "orange-lollipop",
    description: "Yellow Sugar Rush selection — candy-sweet baccatum with a clean citrus snap.",
    special: "One of the highest-yielding sweet hots known.",
    notes: "7-gal fabric allocation to keep the 10-gal fabric list within the real 22-pot limit.",
    priority: "high",
    use_cases: ["fresh eat", "ferment", "hot sauce"],
  }),
  p({
    cultivar: "Pink Habanero",
    plant_code: "OW",
    species: "chinense",
    heat_level: 4,
    flavor_tags: ["fruity", "floral"],
    flavor_subtags: ["tropical", "rose"],
    color_tags: ["purple/pink"],
    age: "OW 2yr+",
    status: "Transplanted",
    current_pot: sevenGalFabric,
    recommended_pot: sevenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🌸",
    description: "Pink-blushed habanero, tropical perfume with a soft floral edge.",
    special: "Pinkish pod color is rare in chinense.",
    notes: "7-gal fabric allocation to preserve 10-gal fabric space for larger VIPs.",
    priority: "high",
    use_cases: ["hot sauce", "ornamental"],
  }),

  // ========== NEW VARIETIES — 10 gal fabric (#1/#2 each) ==========
];

const newToTenGalFabric: Array<Omit<SeedPepper, "plant_code" | "fixed" | "seeded"> & { both?: boolean }> = [
  {
    cultivar: "Venezuelan Tiger",
    species: "chinense",
    heat_level: 0,
    flavor_tags: ["fruity", "sweet", "aromatic/perfume"],
    flavor_subtags: ["tropical", "exotic"],
    color_tags: ["orange", "stripey"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🐅",
    description: "No-heat striped chinense with tropical perfume and unique tiger pod art.",
    special: "Tiger-stripe pods without burn — rare visual and culinary combo.",
    notes: "#1 in 10 gal; #2 in 7 gal.",
    priority: "high",
    use_cases: ["hot sauce", "ornamental"],
    location: "Rooftop",
  },
  {
    cultivar: "Madame Jeanette",
    species: "chinense",
    heat_level: 4,
    flavor_tags: ["fruity", "aromatic/perfume"],
    flavor_subtags: ["tropical", "exotic"],
    color_tags: ["yellow"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "💛",
    description: "Surinamese yellow chinense — bright fruit perfume and intense lingering heat.",
    special: "Backbone of Caribbean cooking.",
    notes: "",
    priority: "high",
    use_cases: ["hot sauce", "fresh eat"],
    location: "Rooftop",
  },
  {
    cultivar: "7 Pot Bubblegum",
    species: "chinense",
    heat_level: 5,
    flavor_tags: ["fruity", "sweet"],
    flavor_subtags: ["berry", "candy"],
    color_tags: ["red", "purple/pink"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "pink-square",
    description: "Superhot 7 Pot variant with sweet bubblegum-fruit aroma and brutal heat.",
    special: "Red calyx and bubblegum nose — star of the bed.",
    notes: "Treat as superhot — 10 gal fabric mandatory.",
    priority: "high",
    use_cases: ["hot sauce", "dehydrate/powder", "seed save"],
    location: "Rooftop",
  },
  {
    cultivar: "Malawi Peppadew",
    species: "chinense",
    heat_level: 1,
    flavor_tags: ["fruity", "sweet"],
    flavor_subtags: ["berry", "candy"],
    color_tags: ["red"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🍒",
    description: "Cherry-shaped sweet pickling pepper with mild fruit pop and gentle warmth.",
    special: "Brand-name peppadew flavor at home.",
    notes: "",
    priority: "normal",
    use_cases: ["ferment", "stuffing", "fresh eat"],
    location: "Rooftop",
  },
  {
    cultivar: "Thunder Mt. Longhorn",
    species: "annuum",
    heat_level: 2,
    flavor_tags: ["fruity", "sweet"],
    flavor_subtags: ["peachy"],
    color_tags: ["red"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🐂",
    description: "Long curling annuum with mild sweet flesh and a striking horn shape.",
    special: "Pods can grow 12+ inches.",
    notes: "Tall plant — likes the volume of a 10 gal.",
    priority: "normal",
    use_cases: ["fresh eat", "stuffing", "dehydrate/powder"],
    location: "Rooftop",
  },
  {
    cultivar: "Thunder Cacho Brown",
    species: "annuum",
    heat_level: 2,
    flavor_tags: ["earthy", "smoky", "sweet"],
    flavor_subtags: ["raisin", "roasted"],
    color_tags: ["brown"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🟫",
    description: "Brown long-horn type with raisin-cocoa depth and a faint smoky edge.",
    special: "Beautiful chocolate-mahogany pods.",
    notes: "",
    priority: "normal",
    use_cases: ["dehydrate/powder", "fresh eat"],
    location: "Rooftop",
  },
  {
    cultivar: "Sugar Rush Peach",
    species: "baccatum",
    heat_level: 2,
    flavor_tags: ["fruity", "sweet"],
    flavor_subtags: ["peachy", "tropical"],
    color_tags: ["orange"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🍑",
    description: "Iconic peach-flavored baccatum, syrupy sweet with playful warmth.",
    special: "Crowd favorite. Insane yields.",
    notes: "",
    priority: "high",
    use_cases: ["fresh eat", "ferment", "hot sauce"],
    location: "Rooftop",
  },
  {
    cultivar: "Scotch Bonnet MOA Yellow",
    species: "chinense",
    heat_level: 4,
    flavor_tags: ["fruity", "aromatic/perfume"],
    flavor_subtags: ["tropical", "exotic"],
    color_tags: ["yellow"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🟡",
    description: "Jamaica MOA selection scotch bonnet — quintessential jerk-pepper aroma.",
    special: "Authentic Jamaican lineage.",
    notes: "",
    priority: "high",
    use_cases: ["hot sauce", "fresh eat", "seed save"],
    location: "Rooftop",
  },
  {
    cultivar: "Lemon Starrburst",
    species: "baccatum",
    heat_level: 3,
    flavor_tags: ["citrus", "fruity"],
    flavor_subtags: ["lemon", "tropical"],
    color_tags: ["yellow"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "yellow-star",
    description: "Yellow baccatum exploding with lemon-candy citrus and clean baccatum heat.",
    special: "Floral lemon nose.",
    notes: "",
    priority: "normal",
    use_cases: ["fresh eat", "ferment"],
    location: "Rooftop",
  },
];

for (const np of newToTenGalFabric) {
  for (const code of ["#1", "#2"]) {
    SEED_PEPPERS.push(p({ ...np, plant_code: code, notes: np.notes ? np.notes : "" }));
  }
}

// Rocoto Costa Rica #1 in 10-gal fabric, #2 in 7-gal fabric backup slot
SEED_PEPPERS.push(
  p({
    cultivar: "Rocoto Costa Rica",
    plant_code: "#1",
    species: "pubescens",
    heat_level: 3,
    flavor_tags: ["fruity", "vegetal/savory", "sweet"],
    flavor_subtags: ["tropical", "grassy"],
    color_tags: ["red"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: tenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "red-pepper",
    description: "Andean pubescens with apple-juicy crunch and a unique fuzzy leaf and black seed.",
    special: "Only species with black seeds; loves cool nights.",
    notes: "Cyprus heat: shade cloth at noon. #1 in 10-gal fabric.",
    priority: "high",
    use_cases: ["fresh eat", "stuffing"],
  }),
  p({
    cultivar: "Rocoto Costa Rica",
    plant_code: "#2",
    species: "pubescens",
    heat_level: 3,
    flavor_tags: ["fruity", "vegetal/savory", "sweet"],
    flavor_subtags: ["tropical", "grassy"],
    color_tags: ["red"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: tenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "red-pepper",
    description: "Andean pubescens with apple-juicy crunch and a unique fuzzy leaf and black seed.",
    special: "Only species with black seeds; loves cool nights.",
    notes: "#2 in 7-gal fabric as backup; give shade cloth and steady moisture.",
    priority: "high",
    use_cases: ["fresh eat", "stuffing"],
  }),
);

// Aji Fantasy Stripey OW in plastic bucket (uses second remaining bucket)
SEED_PEPPERS.push(
  p({
    cultivar: "Aji Fantasy Stripey",
    plant_code: "OW",
    species: "baccatum",
    heat_level: 2,
    flavor_tags: ["fruity", "citrus"],
    flavor_subtags: ["tropical", "lemon"],
    color_tags: ["yellow", "white/cream", "stripey"],
    age: "OW 2yr+",
    status: "Transplanted",
    current_pot: tenGalPlastic,
    recommended_pot: tenGalPlastic,
    ideal_pot: tenGalFabric,
    pot_material: "plastic bucket (light)",
    thumbnail: "🦓",
    description: "Striped baccatum with tropical citrus flavor and a fun zebra-pod look.",
    special: "Pods stripe purple/yellow then ripen red.",
    notes: "Uses one of the 2 remaining 10-gal plastic buckets.",
    priority: "high",
    use_cases: ["ornamental", "fresh eat"],
  }),
);

// 7-gal fabric: duplicates and compact varieties
const sevenGalDoubles: Array<Omit<SeedPepper, "plant_code" | "fixed" | "seeded">> = [
  {
    cultivar: "Aji Charapita",
    species: "frutescens/other",
    heat_level: 3,
    flavor_tags: ["fruity", "citrus"],
    flavor_subtags: ["tropical", "lemon"],
    color_tags: ["yellow"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "yellow-concentric",
    description: "Tiny pea-sized Peruvian gold called the most expensive pepper in the world.",
    special: "Bush stays small but loaded with golden BB pods.",
    notes: "",
    priority: "normal",
    use_cases: ["fresh eat", "seed save", "ornamental"],
    location: "Rooftop",
  },
  {
    cultivar: "Habanada",
    species: "chinense",
    heat_level: 0,
    flavor_tags: ["fruity", "floral", "aromatic/perfume"],
    flavor_subtags: ["tropical", "rose"],
    color_tags: ["orange"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "orange-no",
    description: "Heatless habanero — full tropical perfume with zero burn.",
    special: "Lets non-chiliheads taste true habanero aroma.",
    notes: "",
    priority: "normal",
    use_cases: ["fresh eat", "salsa", "stuffing"],
    location: "Rooftop",
  },
  {
    cultivar: "Lemon Drop",
    species: "baccatum",
    heat_level: 3,
    flavor_tags: ["citrus", "fruity"],
    flavor_subtags: ["lemon"],
    color_tags: ["yellow"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🍋",
    description: "Classic Peruvian aji with bright lemon zip and clean medium burn.",
    special: "Workhorse cooking pepper.",
    notes: "",
    priority: "normal",
    use_cases: ["hot sauce", "fresh eat", "ferment"],
    location: "Rooftop",
  },
  {
    cultivar: "Trinidad Perfume",
    species: "chinense",
    heat_level: 0,
    flavor_tags: ["aromatic/perfume", "floral", "fruity"],
    flavor_subtags: ["tropical", "incense"],
    color_tags: ["yellow"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "🌼",
    description: "Heatless chinense with rich tropical perfume — used as flavor builder.",
    special: "All aroma, zero heat.",
    notes: "",
    priority: "normal",
    use_cases: ["fresh eat", "salsa"],
    location: "Rooftop",
  },
];

for (const np of sevenGalDoubles) {
  for (const code of ["#1", "#2"]) {
    SEED_PEPPERS.push(p({ ...np, plant_code: code }));
  }
}

// Buena Mulata: both need spare 5-7 gal pots
SEED_PEPPERS.push(
  p({
    cultivar: "Buena Mulata",
    plant_code: "#1",
    species: "annuum",
    heat_level: 2,
    flavor_tags: ["fruity", "vegetal/savory"],
    flavor_subtags: ["bell"],
    color_tags: ["purple/pink"],
    age: "seedling",
    status: "Needs pot",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "cup",
    thumbnail: "purple-squiggle",
    description: "Heirloom annuum that ripens through purple, orange, and red on the same plant.",
    special: "Color shift through five stages — natural rainbow plant.",
    notes: "Track for spare 5-7 gal pot. Currently in cup.",
    priority: "low",
    use_cases: ["ornamental", "fresh eat"],
  }),
  p({
    cultivar: "Buena Mulata",
    plant_code: "#2",
    species: "annuum",
    heat_level: 2,
    flavor_tags: ["fruity", "vegetal/savory"],
    flavor_subtags: ["bell"],
    color_tags: ["purple/pink"],
    age: "seedling",
    status: "Needs pot",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "cup",
    thumbnail: "purple-squiggle",
    description: "Heirloom annuum that ripens through purple, orange, and red on the same plant.",
    special: "Color shift through five stages — natural rainbow plant.",
    notes: "Track for spare 5-7 gal pot. Currently in cup.",
    priority: "low",
    use_cases: ["ornamental", "fresh eat"],
  }),
);

// Additional 7-gal pepper added after final allocation
SEED_PEPPERS.push(
  p({
    cultivar: "Biquinho Yellow",
    plant_code: "#1",
    species: "chinense",
    heat_level: 1,
    flavor_tags: ["fruity", "floral", "sweet"],
    flavor_subtags: ["tropical", "honeysuckle", "honey"],
    color_tags: ["green", "yellow"],
    age: "seedling",
    status: "Ready to transplant",
    current_pot: sevenGalFabric,
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "fabric (light)",
    thumbnail: "yellow-teardrop",
    description: "Tiny yellow Brazilian beak pepper with sweet floral fruit and only a touch of heat.",
    special: "Pickling star: crunchy, bright, and chinense-flavored without serious burn.",
    notes: "Added as Biquinho Yellow in a 7-gal pot.",
    priority: "normal",
    use_cases: ["fresh eat", "salsa", "ferment", "ornamental"],
    location: "Rooftop",
  }),
);

// Lower priority / needs pot
const needsPotList: Array<Omit<SeedPepper, "plant_code" | "fixed" | "seeded">> = [
  {
    cultivar: "Cheiro Roxa",
    species: "chinense",
    heat_level: 3,
    flavor_tags: ["floral", "fruity"],
    flavor_subtags: ["rose", "berry"],
    color_tags: ["purple/pink"],
    age: "seedling",
    status: "Needs pot",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "cup",
    thumbnail: "purple-smoke",
    description: "Brazilian small purple chinense with floral rose perfume and balanced heat.",
    special: "Stunning purple pods on compact plants.",
    notes: "Track for spare 5-7 gal pot. Currently in cup.",
    priority: "low",
    use_cases: ["ornamental", "fresh eat", "hot sauce"],
    location: "Rooftop",
  },
  {
    cultivar: "Penis Pepper Red",
    species: "annuum",
    heat_level: 2,
    flavor_tags: ["fruity", "vegetal/savory"],
    flavor_subtags: ["bell"],
    color_tags: ["red"],
    age: "seedling",
    status: "Needs pot",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "cup",
    thumbnail: "red-mushroom",
    description: "Novelty-shaped annuum with mild sweet flesh — purely visual interest.",
    special: "Conversation starter on the rooftop.",
    notes: "Track for 5-7 gal pot.",
    priority: "low",
    use_cases: ["ornamental"],
    location: "Rooftop",
  },
  {
    cultivar: "Holy Mole",
    species: "annuum",
    heat_level: 2,
    flavor_tags: ["smoky", "earthy"],
    flavor_subtags: ["roasted", "raisin"],
    color_tags: ["brown"],
    age: "seedling",
    status: "Needs pot",
    current_pot: "Cups / unassigned",
    recommended_pot: sevenGalFabric,
    ideal_pot: sevenGalFabric,
    pot_material: "cup",
    thumbnail: "brown-cross",
    description: "Pasilla-style annuum with raisin, cocoa, smoke — the mole sauce backbone.",
    special: "Authentic Mexican mole flavor.",
    notes: "Track for 5-7 gal pot.",
    priority: "low",
    use_cases: ["dehydrate/powder", "hot sauce"],
    location: "Rooftop",
  },
];

for (const np of needsPotList) {
  for (const code of ["#1", "#2"]) {
    SEED_PEPPERS.push(p({ ...np, plant_code: code }));
  }
}

function updatePlant(cultivar: string, plant_code: string, updates: Partial<SeedPepper>) {
  const plant = SEED_PEPPERS.find((x) => x.cultivar === cultivar && x.plant_code === plant_code);
  if (!plant) throw new Error(`Missing seed plant: ${cultivar} ${plant_code}`);
  Object.assign(plant, updates);
}

function assignPot(cultivar: string, plant_code: string, pot: string, material = "fabric (light)", note?: string) {
  updatePlant(cultivar, plant_code, {
    recommended_pot: pot,
    ideal_pot: pot === fiveGal ? sevenGalFabric : tenGalFabric,
    pot_material: material,
    notes: note ?? `${plant_code} planned for ${pot}.`,
  });
}

// Final May 10 allocation pass: all buckets consolidated into the 10-gal filter category.
updatePlant("Sugar Rush Amarillo", "OW", {
  current_pot: tenGalFabric,
  recommended_pot: tenGalFabric,
  notes: "Moved up to 10 gal after switching Cheiro Roxa down.",
});
updatePlant("Pink Habanero", "OW", {
  current_pot: tenGalFabric,
  recommended_pot: tenGalFabric,
  notes: "Allocated to 10 gal for stronger OW production.",
});

assignPot("Venezuelan Tiger", "#2", sevenGalFabric, "fabric (light)", "#2 planned for 7 gal; #1 stays in 10 gal.");
assignPot("Malawi Peppadew", "#2", sevenGalFabric, "plastic bucket (light)", "#2 uses the extra 7-gal bucket.");
assignPot("Sugar Rush Peach", "#2", sevenGalFabric);
assignPot("Scotch Bonnet MOA Yellow", "#2", sevenGalFabric);
assignPot("Lemon Starrburst", "#2", sevenGalFabric);
assignPot("Rocoto Costa Rica", "#2", sevenGalFabric);

assignPot("Habanada", "#1", tenGalFabric, "fabric (light)", "#1 gets 10 gal for maximum no-heat chinense flavor yield.");
assignPot("Lemon Drop", "#1", tenGalFabric, "fabric (light)", "#1 gets 10 gal; #2 stays in 7 gal.");
assignPot("Trinidad Perfume", "#1", tenGalFabric, "fabric (light)", "#1 gets 10 gal for aroma harvests; #2 stays in 7 gal.");
assignPot("Holy Mole", "#1", tenGalFabric, "fabric (light)", "#1 gets the remaining 10 gal cooking/powder slot.");

assignPot("7 Pot Bubblegum", "#2", fiveGal, "plastic pot", "#2 stays compact in 5 gal; #1 carries the 10-gal superhot slot.");
assignPot("Aji Charapita", "#1", fiveGal, "plastic pot", "Tiny-pod plant planned for 5 gal.");
assignPot("Aji Charapita", "#2", fiveGal, "plastic pot", "Tiny-pod backup planned for 5 gal.");
assignPot("Cheiro Roxa", "#1", fiveGal, "plastic pot", "#1 in 5 gal; #2 in 7 gal.");
assignPot("Cheiro Roxa", "#2", sevenGalFabric, "fabric (light)", "#2 gets the 7-gal Cheiro Roxa slot.");
assignPot("Penis Pepper Red", "#1", sevenGalFabric, "fabric (light)", "#1 moved from 10 gal to 7 gal.");
assignPot("Penis Pepper Red", "#2", fiveGal, "plastic pot", "#2 backup planned for 5 gal.");
assignPot("Buena Mulata", "#1", sevenGalFabric, "fabric (light)", "#1 moved from 10 gal to 7 gal.");
assignPot("Buena Mulata", "#2", fiveGal, "plastic pot", "#2 backup planned for 5 gal.");
assignPot("Thunder Mt. Longhorn", "#2", tenGalFabric, "fabric (light)", "#2 moved up to 10 gal.");
assignPot("Thunder Cacho Brown", "#2", tenGalFabric, "fabric (light)", "#2 gets the remaining 10-gal slot.");
assignPot("Holy Mole", "#2", fiveGal, "plastic pot", "#2 backup planned for 5 gal.");
