import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { SEED_PEPPERS } from "../server/seed";

const root = resolve(import.meta.dirname, "..");
const logo = readFileSync(resolve(root, "attached_assets/logo.webp")).toString("base64");
const data = SEED_PEPPERS.map((pepper, index) => ({ id: index + 1, ...pepper }));

const html = String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#fff8ec" />
  <title>Guyboo's Burning Rooftop · Offline Pepper Archive</title>
  <style>
    :root{--bg:#f5efe3;--card:#fbf7ed;--ink:#211b16;--muted:#66594c;--line:#3a3129;--accent:#cf261b;--soft:#efe5d3;--stamp:#fff2dc}
    *{box-sizing:border-box}html{background:var(--bg)}body{margin:0;min-height:100vh;background:radial-gradient(circle at 20% 10%,rgba(207,38,27,.055) 0,transparent 360px),radial-gradient(circle at 80% 90%,rgba(207,38,27,.04) 0,transparent 360px),var(--bg);color:var(--ink);font-family:"DM Sans",system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    .display,h2,.tileTitle,.name,.idTitle{font-family:"Bebas Neue","Arial Narrow","Impact",sans-serif;letter-spacing:.055em;font-weight:800}.script{font-family:"Caveat","Comic Sans MS",cursive;color:var(--accent);font-size:30px;font-weight:800;line-height:.82}
    header{position:sticky;top:0;z-index:20;background:rgba(245,239,227,.96);backdrop-filter:blur(10px);border-bottom:2px solid var(--line)}
    .wrap{max-width:1152px;margin:0 auto;padding:12px 16px}.brand{display:flex;gap:12px;align-items:center}.brand img{width:98px;height:48px;object-fit:contain;border:2px solid var(--line);border-radius:5px;background:var(--card);padding:4px}.block{font-family:"Bebas Neue","Arial Narrow","Impact",sans-serif;font-size:19px;letter-spacing:.09em;font-weight:900}
    .top{display:flex;flex-direction:column;gap:10px;margin:22px 0 14px}.topRow{display:flex;gap:10px;align-items:center}.searchWrap{position:relative;flex:1}.searchIcon{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:var(--muted)}.search{width:100%;border:2px solid var(--line);border-radius:6px;background:var(--card);padding:12px 14px 12px 38px;font-size:16px;outline:none}.search:focus{box-shadow:0 0 0 3px rgba(207,38,27,.15)}.count{white-space:nowrap;color:var(--muted);font-weight:800;font-size:14px}
    h2{font-size:24px;margin:18px 0 12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.pos,.tile,.card,.panel{background:var(--card);border:2px solid var(--line);border-radius:7px;box-shadow:4px 4px 0 rgba(58,49,41,.92)}button{font:inherit;color:inherit}.tile{min-height:132px;text-align:left;padding:18px;display:flex;flex-direction:column;justify-content:space-between}.tileIcon{font-size:25px;line-height:1}.tileTitle{font-size:25px;line-height:1}.tile small{display:block;color:var(--muted);font-weight:500;letter-spacing:0;font-size:12px;margin-top:8px}.tile:hover{transform:translate(-2px,-2px);box-shadow:6px 6px 0 var(--line)}.tile:active,.btn:active,.card:active{transform:translate(2px,2px);box-shadow:1px 1px 0 var(--line)}
    .btn{border:2px solid var(--line);border-radius:6px;background:var(--card);padding:9px 12px;font-weight:900;box-shadow:2px 2px 0 rgba(58,49,41,.75)}.btn.primary{background:var(--accent);color:#fffaf0}.btn.small{font-size:12px;padding:7px 10px;box-shadow:none}.chips,.actions{display:flex;gap:8px;flex-wrap:wrap}.actions{align-items:center;margin-bottom:10px}.chip,.badge,.tag{border:2px solid var(--line);background:var(--card);border-radius:999px;padding:5px 9px;font-size:12px;font-weight:800}.chip.on{background:var(--accent);color:#fffaf0}.badge{border-width:1.5px;background:var(--stamp);cursor:pointer}
    .panel{padding:0;margin:12px 0 16px;box-shadow:2px 2px 0 rgba(58,49,41,.65);overflow:hidden}.panelHead{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px}.panelHead b{font-family:"Bebas Neue","Arial Narrow","Impact",sans-serif;font-size:18px;letter-spacing:.06em}.filters{display:none;gap:12px;overflow:auto;padding:12px;border-top:2px solid var(--line);background:rgba(255,255,255,.24)}.filters.open{display:flex}.group{min-width:190px;border:2px solid var(--line);border-radius:7px;background:rgba(251,247,237,.82);padding:9px}.group b{display:block;font-family:"Bebas Neue","Arial Narrow","Impact",sans-serif;font-size:14px;color:var(--muted);letter-spacing:.09em;margin-bottom:6px}.group label{display:flex;gap:8px;align-items:center;margin:7px 0;font-size:13px;text-transform:capitalize;min-height:24px}.group input{accent-color:var(--accent)}
    .results{display:grid;grid-template-columns:1fr;gap:12px}.card{padding:14px;display:flex;flex-direction:column;gap:9px;text-align:left;width:100%;cursor:pointer}.cardTop{display:flex;align-items:flex-start;gap:12px}.thumbBox{width:56px;height:56px;flex:0 0 56px;border:2px solid var(--line);border-radius:7px;background:var(--soft);display:flex;align-items:center;justify-content:center;font-size:32px}.nameRow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.name{font-size:24px;line-height:.95}.code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:var(--muted)}.meta{color:var(--muted);font-size:12px;font-style:italic;margin-top:2px}.badges{display:flex;flex-wrap:wrap;gap:6px}.cardFields{border-top:1.5px solid var(--line);padding-top:9px;display:grid;grid-template-columns:1fr 1fr;gap:7px 12px;font-size:12px}.fieldLabel{color:var(--muted);font-size:11px}.fieldValue{color:var(--ink)}
    dialog{border:2px solid var(--line);border-radius:9px;box-shadow:8px 8px 0 var(--line);max-width:560px;width:calc(100vw - 28px);background:var(--card);color:var(--ink);padding:18px}dialog::backdrop{background:rgba(0,0,0,.42)}.dialogHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.idHero{display:flex;gap:12px;align-items:flex-start}.idTitle{font-size:31px;line-height:.95}.tags{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.special{border:2px solid var(--line);border-radius:7px;background:var(--card);padding:12px;margin:12px 0}.specialTitle{font-family:"Bebas Neue","Arial Narrow","Impact",sans-serif;font-size:14px;letter-spacing:.08em;color:var(--muted);margin-bottom:5px}.idGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;font-size:13px;margin-top:12px}.notes{border-top:2px solid var(--line);margin-top:13px;padding-top:11px;font-family:"Caveat","Comic Sans MS",cursive;font-size:18px;line-height:1.15}
    form{display:grid;gap:8px}input,select,textarea{border:2px solid var(--line);border-radius:6px;background:#fffdf8;padding:10px;font:inherit}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hidden{display:none!important}.note{border:2px dashed var(--line);border-radius:7px;padding:18px;color:var(--muted);font-size:13px;margin-top:24px;text-align:center}.subtle{color:var(--muted);font-size:13px}.offlineStamp{margin-left:auto;border:2px solid var(--line);border-radius:5px;padding:6px 8px;font-size:12px;font-weight:900;background:var(--card)}
    @media(min-width:640px){.top{flex-direction:row;align-items:center;justify-content:space-between}.searchWrap{max-width:580px}.brand img{width:130px;height:55px}.script{font-size:34px}.grid{grid-template-columns:repeat(3,1fr)}.results{grid-template-columns:repeat(2,1fr)}}
    @media(min-width:1024px){.grid{grid-template-columns:repeat(4,1fr)}.results{grid-template-columns:repeat(3,1fr)}.tile{min-height:150px}.wrap{padding-left:20px;padding-right:20px}}
  </style>
</head>
<body>
  <header><div class="wrap brand"><img src="data:image/webp;base64,${logo}" alt="Guyboo's Burning Rooftop logo"/><div><div class="script">Guyboo's</div><div class="block">BURNING ROOFTOP · LARNACA</div></div><div class="offlineStamp">OFFLINE</div></div></header>
  <main class="wrap">
    <div class="top"><div class="searchWrap"><span class="searchIcon">⌕</span><input id="search" class="search" type="search" placeholder="Search cultivar, flavor, notes..." /></div><span id="count" class="count"></span></div>
    <section id="home"><h2>FILTER BY</h2><div class="grid" id="homeGrid"></div><div class="note">Offline file. Filters and ID cards work without internet. New entries are saved in this browser/file storage when available; use Export Backup to keep a copy.</div></section>
    <section id="options" class="hidden"><div class="actions"><button class="btn small" onclick="goHome()">‹ Home</button></div><h2 id="optionTitle"></h2><div class="grid" id="optionGrid"></div></section>
    <section id="results" class="hidden"><div class="actions"><button class="btn small" onclick="goHome()">‹ Home</button><button class="btn small" onclick="clearFilters()">Clear</button><button class="btn small" onclick="openAdd()">+ Add</button><button class="btn small" onclick="exportBackup()">Export Backup</button></div><h2 id="resultTitle">Full Garden</h2><div class="panel"><div class="panelHead"><b>REFINE RESULTS</b><button class="btn small" onclick="toggleRefine()" id="refineBtn">Show filters</button></div><div class="filters" id="refine"></div></div><div class="chips" id="activeChips"></div><div class="results" id="cards"></div></section>
  </main>
  <dialog id="idDialog"><div id="idContent"></div></dialog>
  <dialog id="addDialog">
    <div class="dialogHead"><div class="idTitle">Add pepper</div><button class="btn small" onclick="closeAdd()">Close</button></div>
    <p class="subtle">Password protected. Offline entries stay on this device/browser when storage is available.</p>
    <form id="addForm">
      <input name="password" type="password" placeholder="Password" required />
      <div class="two"><input name="cultivar" placeholder="Cultivar" required /><input name="plant_code" placeholder="Plant code, e.g. #1" required /></div>
      <div class="two"><select name="species"></select><select name="heat_level"></select></div>
      <div class="two"><select name="current_pot"></select><input name="thumbnail" placeholder="Emoji thumbnail" value="🌶️" /></div>
      <input name="colors" placeholder="Colors, comma separated: red, purple/pink..." />
      <input name="flavors" placeholder="Flavors, comma separated: fruity, citrus..." />
      <textarea name="description" placeholder="Short description"></textarea>
      <textarea name="special" placeholder="What makes it special"></textarea>
      <button class="btn primary" type="submit">Save pepper</button>
    </form>
  </dialog>
  <script>
    const BASE = ${JSON.stringify(data)};
    const PASSWORD = "03041989";
    const TAX = {
      pot_size:["5 gal","7 gal","10 gal"],
      heat_level:[0,1,2,3,4,5],
      flavor:["fruity","earthy","smoky","floral","citrus","sweet","aromatic/perfume","vegetal/savory"],
      color:["green","red","yellow","orange","purple/pink","white/cream","brown","stripey"],
      species:["chinense","baccatum","annuum","pubescens","frutescens/other"],
      use_case:["fresh eat","salsa","hot sauce","dehydrate/powder","stuffing","ferment","ornamental","seed save"]
    };
    const HEAT = ["No heat","Mild","Warm","Hot","Fiery","Inferno"];
    const CATS = [
      ["see_all","Full Garden","every plant","⌖"],["pot_size","Pot Size","5–10 gal","▰"],["heat_level","Heat Level","0 → 5 flames","♨"],["flavor","Flavor","fruity, smoky, citrus...","▱"],["color","Color","pink, brown, stripey...","◔"],["species","Species","chinense, baccatum...","♧"],["use_case","Use Case","sauce · ferment · dehydrate","◇"]
    ];
    let peppers = loadPeppers();
    let filters = {pot_size:[],heat_level:[],flavor:[],color:[],species:[],use_case:[]};
    let active = null;
    function loadPeppers(){try{return [...BASE,...JSON.parse(localStorage.getItem("gbr_extra_peppers")||"[]")]}catch{return BASE.slice()}}
    function saveExtra(p){try{const extra=JSON.parse(localStorage.getItem("gbr_extra_peppers")||"[]");extra.push(p);localStorage.setItem("gbr_extra_peppers",JSON.stringify(extra))}catch(e){alert("Saved for this session only. Export a backup to keep it.")}}
    function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
    function heat(n){return (Number(n)? "🔥".repeat(Number(n)) : "•")+" "+HEAT[Number(n)]}
    function matches(p){const q=document.getElementById("search").value.trim().toLowerCase(); if(filters.pot_size.length && !filters.pot_size.includes(p.current_pot)&&!filters.pot_size.includes(p.recommended_pot))return false; if(filters.heat_level.length&&!filters.heat_level.includes(p.heat_level))return false; if(filters.flavor.length&&!filters.flavor.some(x=>(p.flavor_tags||[]).includes(x)))return false; if(filters.color.length&&!filters.color.some(x=>(p.color_tags||[]).includes(x)))return false; if(filters.species.length&&!filters.species.includes(p.species))return false; if(filters.use_case.length&&!filters.use_case.some(x=>(p.use_cases||[]).includes(x)))return false; if(q){const hay=[p.cultivar,p.plant_code,p.species,p.description,p.special,p.notes,...(p.flavor_tags||[]),...(p.flavor_subtags||[]),...(p.color_tags||[])].join(" ").toLowerCase(); if(!hay.includes(q))return false} return true}
    function renderHome(){homeGrid.innerHTML=CATS.map(([k,l,s,i])=>'<button class="tile" data-cat="'+esc(k)+'"><span class="tileIcon">'+esc(i)+'</span><span><span class="tileTitle">'+esc(l)+'</span><small>'+esc(s)+'</small></span></button>').join(""); homeGrid.querySelectorAll("button").forEach(btn=>btn.onclick=()=>openCat(btn.dataset.cat)); count.textContent=peppers.length+" / "+peppers.length+" plants"}
    function openCat(k){active=k; if(k==="see_all"){showResults("Full Garden");return} home.classList.add("hidden"); results.classList.add("hidden"); options.classList.remove("hidden"); optionTitle.textContent=CATS.find(c=>c[0]===k)[1]; optionGrid.innerHTML=TAX[k].map(v=>'<button class="tile" data-value="'+esc(v)+'"><span class="tileIcon">'+esc(k==="heat_level"?"♨":"•")+'</span><span><span class="tileTitle">'+esc(k==="heat_level"?heat(v):v)+'</span></span></button>').join(""); optionGrid.querySelectorAll("button").forEach(btn=>btn.onclick=()=>selectOne(k,btn.dataset.value))}
    function selectOne(k,v){filters[k]=[k==="heat_level"?Number(v):v]; showResults()}
    function showResults(title){home.classList.add("hidden"); options.classList.add("hidden"); results.classList.remove("hidden"); resultTitle.textContent=title||"Results"; renderRefine(); renderResults()}
    function renderResults(){const list=peppers.filter(matches); count.textContent=list.length+" / "+peppers.length+" plants"; activeChips.innerHTML=Object.entries(filters).flatMap(([k,a])=>a.map(v=>'<button class="chip on" data-key="'+esc(k)+'" data-value="'+esc(v)+'">'+esc(k==="heat_level"?heat(v):v)+' ×</button>')).join(""); activeChips.querySelectorAll("button").forEach(btn=>btn.onclick=()=>toggleFilter(btn.dataset.key,btn.dataset.value)); cards.innerHTML=list.map(p=>'<button class="card" data-id="'+p.id+'"><span class="cardTop"><span class="thumbBox">'+esc(p.thumbnail||"🌶️")+'</span><span><span class="nameRow"><span class="name">'+esc(p.cultivar)+'</span><span class="code">'+esc(p.plant_code||"")+'</span>'+(p.fixed?'<span class="badge">▣ FIXED</span>':"")+'</span><span class="meta">'+esc(p.species)+' · '+esc(p.age||"")+'</span></span></span><span class="badges"><span class="badge">♨ '+esc(heat(p.heat_level))+' <span class="subtle">'+esc(p.heat_level)+'/5</span></span>'+(p.color_tags||[]).map(c=>'<span class="badge">'+esc(c)+'</span>').join("")+(p.flavor_tags||[]).slice(0,3).map(f=>'<span class="badge">'+esc(f)+'</span>').join("")+'</span><span class="cardFields"><span><span class="fieldLabel">Current pot</span><br><span class="fieldValue">'+esc(p.current_pot)+'</span></span><span><span class="fieldLabel">Recommended</span><br><span class="fieldValue">'+esc(p.recommended_pot||"—")+'</span></span><span><span class="fieldLabel">Status</span><br><span class="fieldValue">'+esc(p.status)+'</span></span><span><span class="fieldLabel">Location</span><br><span class="fieldValue">'+esc(p.location)+'</span></span></span></button>').join("")||'<div class="note">No matching peppers.</div>'; cards.querySelectorAll("button").forEach(btn=>btn.onclick=()=>openId(Number(btn.dataset.id)))}
    function renderRefine(){refine.innerHTML=Object.entries(TAX).map(([k,vals])=>'<div class="group"><b>'+esc(k.replace("_"," "))+'</b>'+vals.map(v=>'<label><input type="checkbox" data-key="'+esc(k)+'" data-value="'+esc(v)+'" '+(filters[k].includes(v)?"checked":"")+'> '+esc(k==="heat_level"?heat(v):v)+'</label>').join("")+'</div>').join(""); refine.querySelectorAll("input").forEach(input=>input.onchange=()=>toggleFilter(input.dataset.key,input.dataset.value))}
    function toggleRefine(){refine.classList.toggle("open"); refineBtn.textContent=refine.classList.contains("open")?"Hide filters":"Show filters"}
    function toggleFilter(k,v){v=k==="heat_level"?Number(v):v; const a=filters[k]; filters[k]=a.includes(v)?a.filter(x=>x!==v):[...a,v]; renderRefine(); renderResults()}
    function clearFilters(){filters={pot_size:[],heat_level:[],flavor:[],color:[],species:[],use_case:[]}; document.getElementById("search").value=""; renderRefine(); renderResults()}
    function goHome(){active=null; clearFilters(); results.classList.add("hidden"); options.classList.add("hidden"); home.classList.remove("hidden"); count.textContent=peppers.length+" / "+peppers.length+" plants"}
    function openId(id){const p=peppers.find(x=>x.id===id); idContent.innerHTML='<div class="dialogHead"><div class="idHero"><span class="thumbBox">'+esc(p.thumbnail||"🌶️")+'</span><span><span class="idTitle">'+esc(p.cultivar)+' <span class="code">'+esc(p.plant_code||"")+'</span></span><br><span class="subtle">Capsicum '+esc(p.species)+' · '+esc(p.age||"")+'</span></span></div><button class="btn small" onclick="idDialog.close()">Close</button></div><p>'+esc(p.description||"Pepper archive entry.")+'</p><div class="tags"><span class="tag">♨ '+esc(heat(p.heat_level))+' '+esc(p.heat_level)+'/5</span>'+[...(p.color_tags||[]),...(p.flavor_tags||[]),...(p.flavor_subtags||[])].map(t=>'<span class="tag">'+esc(t)+'</span>').join("")+'</div>'+(p.special?'<div class="special"><div class="specialTitle">✦ WHAT MAKES IT SPECIAL</div>'+esc(p.special)+'</div>':"")+'<div class="idGrid"><span><span class="fieldLabel">Current pot</span><br>'+esc(p.current_pot)+'</span><span><span class="fieldLabel">Recommended</span><br>'+esc(p.recommended_pot||"—")+'</span><span><span class="fieldLabel">Ideal pot</span><br>'+esc(p.ideal_pot||"—")+'</span><span><span class="fieldLabel">Pot material</span><br>'+esc(p.pot_material||"—")+'</span><span><span class="fieldLabel">Status</span><br>'+esc(p.status)+'</span><span><span class="fieldLabel">Use cases</span><br>'+esc((p.use_cases||[]).join(", ")||"—")+'</span></div>'+(p.notes?'<div class="notes">'+esc(p.notes)+'</div>':""); idDialog.showModal()}
    function openAdd(){addDialog.showModal()} function closeAdd(){addDialog.close()}
    function fillForm(){document.querySelector("[name=species]").innerHTML=TAX.species.map(x=>'<option>'+esc(x)+'</option>').join("");document.querySelector("[name=heat_level]").innerHTML=TAX.heat_level.map(x=>'<option value="'+x+'">'+esc(heat(x))+'</option>').join("");document.querySelector("[name=current_pot]").innerHTML=TAX.pot_size.map(x=>'<option>'+esc(x)+'</option>').join("")}
    addForm.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(addForm);if(f.get("password")!==PASSWORD){alert("Wrong password");return}const p={id:Date.now(),cultivar:f.get("cultivar"),plant_code:f.get("plant_code"),species:f.get("species"),heat_level:Number(f.get("heat_level")),flavor_tags:String(f.get("flavors")||"").split(",").map(s=>s.trim()).filter(Boolean),flavor_subtags:[],color_tags:String(f.get("colors")||"").split(",").map(s=>s.trim()).filter(Boolean),age:"new",status:"Added offline",current_pot:f.get("current_pot"),recommended_pot:f.get("current_pot"),ideal_pot:f.get("current_pot"),pot_material:"",location:"Rooftop",thumbnail:f.get("thumbnail")||"🌶️",description:f.get("description")||"",special:f.get("special")||"",notes:"Added in offline file",priority:"normal",use_cases:[],fixed:false,seeded:false};peppers.push(p);saveExtra(p);addDialog.close();showResults("Full Garden")});
    function exportBackup(){const blob=new Blob([JSON.stringify(peppers,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="guyboos-pepper-garden-backup.json";a.click();URL.revokeObjectURL(a.href)}
    search.addEventListener("input",()=>{if(!results.classList.contains("hidden"))renderResults()});
    fillForm(); renderHome();
  </script>
</body>
</html>`;

writeFileSync(resolve(root, "..", "guyboos-burning-rooftop-offline.html"), html);
console.log(`wrote ${data.length} peppers to guyboos-burning-rooftop-offline.html`);
